apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio
        args: ["server","/data","--console-address",":9001"]
        env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://minio.console.169.254.33.170.sslip.io"
        - name: MINIO_SERVER_URL
          value: "http://minio.169.254.33.170.sslip.io"
        ports:
        - containerPort: 9000
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      name: minio
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: minio-console
      port: 9001
      targetPort: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myserviceb
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: minio.169.254.33.170.sslip.io
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: minio
            port:
              number: 9000
  - host: minio.console.169.254.33.170.sslip.io
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: minio
            port:
              number: 9001
